spring:
    datasource:
        sql-script-encoding: UTF-8
        platform: h2
        url: jdbc:h2:mem:backup
        username: sa
        password:
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create
    thymeleaf:
        cache: false
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
            
---
spring:
    profiles: dev
    datasource:
        platform: mysql
        url: jdbc:mysql://localhost:3306/backupdemo?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: doc
    jpa:
        hibernate:
            ddl-auto: update
    thymeleaf:
        cache: false
---
spring:
    profiles: test
    datasource:
        platform: mssql
        url: jdbc:sqlserver://193.124.66.210
        username: logadmin
        password: vn34-Dn
    jpa:
        hibernate:
            ddl-auto: update
---
spring:
    profiles: production
    datasource:
        url: jdbc:mysql://localhost:3306/demobackup
        username: root
        password: doc
    jpa:
        hibernate:
            ddl-auto: update
